apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: hj49wo85v-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hj49wo85v-python 
  name: hj49wo85v-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hj49wo85v-python
    weight: 100 
