apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hj49wo85v-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hj49wo85v-python 
  name: hj49wo85v-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hj49wo85v-python 
